// Code generated by go-swagger; DO NOT EDIT.

package card_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tooolbox/firstvision/models"
)

// ValidateCvv2V1FvEmeaReader is a Reader for the ValidateCvv2V1FvEmea structure.
type ValidateCvv2V1FvEmeaReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ValidateCvv2V1FvEmeaReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewValidateCvv2V1FvEmeaOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewValidateCvv2V1FvEmeaBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewValidateCvv2V1FvEmeaUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewValidateCvv2V1FvEmeaForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewValidateCvv2V1FvEmeaNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewValidateCvv2V1FvEmeaTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 452:
		result := NewValidateCvv2V1FvEmeaStatus452()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 453:
		result := NewValidateCvv2V1FvEmeaStatus453()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 455:
		result := NewValidateCvv2V1FvEmeaStatus455()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewValidateCvv2V1FvEmeaOK creates a ValidateCvv2V1FvEmeaOK with default headers values
func NewValidateCvv2V1FvEmeaOK() *ValidateCvv2V1FvEmeaOK {
	return &ValidateCvv2V1FvEmeaOK{}
}

/*ValidateCvv2V1FvEmeaOK handles this case with default header values.

successful operation
*/
type ValidateCvv2V1FvEmeaOK struct {
	Payload *models.ValidateCvv2Response
}

func (o *ValidateCvv2V1FvEmeaOK) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/validateCvv2][%d] validateCvv2V1FvEmeaOK  %+v", 200, o.Payload)
}

func (o *ValidateCvv2V1FvEmeaOK) GetPayload() *models.ValidateCvv2Response {
	return o.Payload
}

func (o *ValidateCvv2V1FvEmeaOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ValidateCvv2Response)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewValidateCvv2V1FvEmeaBadRequest creates a ValidateCvv2V1FvEmeaBadRequest with default headers values
func NewValidateCvv2V1FvEmeaBadRequest() *ValidateCvv2V1FvEmeaBadRequest {
	return &ValidateCvv2V1FvEmeaBadRequest{}
}

/*ValidateCvv2V1FvEmeaBadRequest handles this case with default header values.

Below are the error codes you can expect when connecting over internet:<BR/><BR/>API-Sec-003 - Invalid request. This could be because of invalid data in the request or header, among other reasons.<BR/>API-Sec-004 - Invalid request. The client_assertion JWT is invalid<BR/>API-Sec-013 - The JWT has an invalid expiry. Pleases end a request with a valid JWT
*/
type ValidateCvv2V1FvEmeaBadRequest struct {
	Payload *models.FsErrorDetails
}

func (o *ValidateCvv2V1FvEmeaBadRequest) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/validateCvv2][%d] validateCvv2V1FvEmeaBadRequest  %+v", 400, o.Payload)
}

func (o *ValidateCvv2V1FvEmeaBadRequest) GetPayload() *models.FsErrorDetails {
	return o.Payload
}

func (o *ValidateCvv2V1FvEmeaBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FsErrorDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewValidateCvv2V1FvEmeaUnauthorized creates a ValidateCvv2V1FvEmeaUnauthorized with default headers values
func NewValidateCvv2V1FvEmeaUnauthorized() *ValidateCvv2V1FvEmeaUnauthorized {
	return &ValidateCvv2V1FvEmeaUnauthorized{}
}

/*ValidateCvv2V1FvEmeaUnauthorized handles this case with default header values.

Unauthorized: Authorization failed due to missing or invalid credentials. <BR/>Below are the error codes you can expect when connecting over internet:<BR/><BR/>API-Sec-001 - The auth header has invalid values. Please try with valid values<BR/>API-Sec-002 - The client id provided is invalid. Please try with valid client id<BR/>API-Sec-007 - The access token is invalid. It may have expired, or maybe incorrect
*/
type ValidateCvv2V1FvEmeaUnauthorized struct {
	Payload *models.FsErrorDetails
}

func (o *ValidateCvv2V1FvEmeaUnauthorized) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/validateCvv2][%d] validateCvv2V1FvEmeaUnauthorized  %+v", 401, o.Payload)
}

func (o *ValidateCvv2V1FvEmeaUnauthorized) GetPayload() *models.FsErrorDetails {
	return o.Payload
}

func (o *ValidateCvv2V1FvEmeaUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FsErrorDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewValidateCvv2V1FvEmeaForbidden creates a ValidateCvv2V1FvEmeaForbidden with default headers values
func NewValidateCvv2V1FvEmeaForbidden() *ValidateCvv2V1FvEmeaForbidden {
	return &ValidateCvv2V1FvEmeaForbidden{}
}

/*ValidateCvv2V1FvEmeaForbidden handles this case with default header values.

Forbidden: Insufficient access for requested operation. <BR/>Below are the error codes you can expect when connecting over internet:<BR/><BR/>API-Sec-006 - Replay attack detected. Please try again with valid data<BR/>API-Sec-008 - Mismatch in scope. The access token does not have the permission to access this resource
*/
type ValidateCvv2V1FvEmeaForbidden struct {
	Payload *models.FsErrorDetails
}

func (o *ValidateCvv2V1FvEmeaForbidden) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/validateCvv2][%d] validateCvv2V1FvEmeaForbidden  %+v", 403, o.Payload)
}

func (o *ValidateCvv2V1FvEmeaForbidden) GetPayload() *models.FsErrorDetails {
	return o.Payload
}

func (o *ValidateCvv2V1FvEmeaForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FsErrorDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewValidateCvv2V1FvEmeaNotFound creates a ValidateCvv2V1FvEmeaNotFound with default headers values
func NewValidateCvv2V1FvEmeaNotFound() *ValidateCvv2V1FvEmeaNotFound {
	return &ValidateCvv2V1FvEmeaNotFound{}
}

/*ValidateCvv2V1FvEmeaNotFound handles this case with default header values.

Below are the error codes you can expect when connecting over internet:<BR/><BR/>API-Sec-005 - Resource not found
*/
type ValidateCvv2V1FvEmeaNotFound struct {
	Payload *models.FsErrorDetails
}

func (o *ValidateCvv2V1FvEmeaNotFound) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/validateCvv2][%d] validateCvv2V1FvEmeaNotFound  %+v", 404, o.Payload)
}

func (o *ValidateCvv2V1FvEmeaNotFound) GetPayload() *models.FsErrorDetails {
	return o.Payload
}

func (o *ValidateCvv2V1FvEmeaNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FsErrorDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewValidateCvv2V1FvEmeaTooManyRequests creates a ValidateCvv2V1FvEmeaTooManyRequests with default headers values
func NewValidateCvv2V1FvEmeaTooManyRequests() *ValidateCvv2V1FvEmeaTooManyRequests {
	return &ValidateCvv2V1FvEmeaTooManyRequests{}
}

/*ValidateCvv2V1FvEmeaTooManyRequests handles this case with default header values.

Below are the error codes you can expect when connecting over internet:<BR/><BR/>API-Sec-009 - You have exceeded the App level quota<BR/>API-Sec-010 - You have exceeded the Developer level quota<BR/>API-Sec-011 - You have exceeded the Product level quota<BR/>API-Sec-012 - Too many requests for this API. Please try after sometime
*/
type ValidateCvv2V1FvEmeaTooManyRequests struct {
	Payload *models.FsErrorDetails
}

func (o *ValidateCvv2V1FvEmeaTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/validateCvv2][%d] validateCvv2V1FvEmeaTooManyRequests  %+v", 429, o.Payload)
}

func (o *ValidateCvv2V1FvEmeaTooManyRequests) GetPayload() *models.FsErrorDetails {
	return o.Payload
}

func (o *ValidateCvv2V1FvEmeaTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FsErrorDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewValidateCvv2V1FvEmeaStatus452 creates a ValidateCvv2V1FvEmeaStatus452 with default headers values
func NewValidateCvv2V1FvEmeaStatus452() *ValidateCvv2V1FvEmeaStatus452 {
	return &ValidateCvv2V1FvEmeaStatus452{}
}

/*ValidateCvv2V1FvEmeaStatus452 handles this case with default header values.

System Exception: Internal processes not related to client interaction with application are the cause of the failure
*/
type ValidateCvv2V1FvEmeaStatus452 struct {
}

func (o *ValidateCvv2V1FvEmeaStatus452) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/validateCvv2][%d] validateCvv2V1FvEmeaStatus452 ", 452)
}

func (o *ValidateCvv2V1FvEmeaStatus452) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewValidateCvv2V1FvEmeaStatus453 creates a ValidateCvv2V1FvEmeaStatus453 with default headers values
func NewValidateCvv2V1FvEmeaStatus453() *ValidateCvv2V1FvEmeaStatus453 {
	return &ValidateCvv2V1FvEmeaStatus453{}
}

/*ValidateCvv2V1FvEmeaStatus453 handles this case with default header values.

Validation Exception: The request failed validation, modify the request and resubmit
*/
type ValidateCvv2V1FvEmeaStatus453 struct {
}

func (o *ValidateCvv2V1FvEmeaStatus453) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/validateCvv2][%d] validateCvv2V1FvEmeaStatus453 ", 453)
}

func (o *ValidateCvv2V1FvEmeaStatus453) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewValidateCvv2V1FvEmeaStatus455 creates a ValidateCvv2V1FvEmeaStatus455 with default headers values
func NewValidateCvv2V1FvEmeaStatus455() *ValidateCvv2V1FvEmeaStatus455 {
	return &ValidateCvv2V1FvEmeaStatus455{}
}

/*ValidateCvv2V1FvEmeaStatus455 handles this case with default header values.

ODS Error Exception: ODS returned a message with transaction status ERROR
*/
type ValidateCvv2V1FvEmeaStatus455 struct {
}

func (o *ValidateCvv2V1FvEmeaStatus455) Error() string {
	return fmt.Sprintf("[POST /fv_emea/v1/validateCvv2][%d] validateCvv2V1FvEmeaStatus455 ", 455)
}

func (o *ValidateCvv2V1FvEmeaStatus455) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
